import { navbar } from "vuepress-theme-hope";

export default navbar([
  "/",
  "/demo/",
  "/vue-design-patterns/",
  {
    text: "博文",
    icon: "pen-to-square",
    prefix: "/column/",
    children: [
      {
        text: "重学数据结构与算法",
        icon: "pen-to-square",
        prefix: "重学数据结构与算法/",
        children: [
          { text: "00 数据结构与算法，应该这样学！", icon: "pen-to-square", link: "00 数据结构与算法，应该这样学！" },
          { text: "01 复杂度：如何衡量程序运行的效率？", icon: "pen-to-square", link: "01 复杂度：如何衡量程序运行的效率？" },
          { text: "02 数据结构：将“昂贵”的时间复杂度转换成“廉价”的空间复杂度", icon: "pen-to-square", link: "02 数据结构：将“昂贵”的时间复杂度转换成“廉价”的空间复杂度" },
          { text: "03 增删查：掌握数据处理的基本操作,以不变应万变", icon: "pen-to-square", link: "03 增删查：掌握数据处理的基本操作,以不变应万变" },
          { text: "04 如何完成线性表结构下的增删查？", icon: "pen-to-square", link: "04 如何完成线性表结构下的增删查？" },
          { text: "05 栈：后进先出的线性表，如何实现增删查？", icon: "pen-to-square", link: "05 栈：后进先出的线性表，如何实现增删查？" },
          { text: "06 队列：先进先出的线性表，如何实现增删查？", icon: "pen-to-square", link: "06 队列：先进先出的线性表，如何实现增删查？" },
          { text: "07 数组：如何实现基于索引的查找？", icon: "pen-to-square", link: "07 数组：如何实现基于索引的查找？" },
          { text: "08 字符串：如何正确回答面试中高频考察的字符串匹配算法？", icon: "pen-to-square", link: "08 字符串：如何正确回答面试中高频考察的字符串匹配算法？" },
          { text: "09 树和二叉树：分支关系与层次结构下，如何有效实现增删查？", icon: "pen-to-square", link: "09 树和二叉树：分支关系与层次结构下，如何有效实现增删查？" },
          { text: "10 哈希表：如何利用好高效率查找的“利器”？", icon: "pen-to-square", link: "10 哈希表：如何利用好高效率查找的“利器”？" },
          { text: "11 递归：如何利用递归求解汉诺塔问题？", icon: "pen-to-square", link: "11 递归：如何利用递归求解汉诺塔问题？" },
          { text: "12 分治：如何利用分治法完成数据查找？", icon: "pen-to-square", link: "12 分治：如何利用分治法完成数据查找？" },
          { text: "13 排序：经典排序算法原理解析与优劣对比", icon: "pen-to-square", link: "13 排序：经典排序算法原理解析与优劣对比" },
          { text: "14 动态规划：如何通过最优子结构，完成复杂问题求解？", icon: "pen-to-square", link: "14 动态规划：如何通过最优子结构，完成复杂问题求解？" },
          { text: "15 定位问题才能更好地解决问题：开发前的复杂度分析与技术选型", icon: "pen-to-square", link: "15 定位问题才能更好地解决问题：开发前的复杂度分析与技术选型" },
          { text: "16 真题案例（一）：算法思维训练", icon: "pen-to-square", link: "16 真题案例（一）：算法思维训练" },
          { text: "17 真题案例（二）：数据结构训练", icon: "pen-to-square", link: "17 真题案例（二）：数据结构训练" },
          { text: "18 真题案例（三）：力扣真题训练", icon: "pen-to-square", link: "18 真题案例（三）：力扣真题训练" },
          { text: "19 真题案例（四）：大厂真题实战演练", icon: "pen-to-square", link: "19 真题案例（四）：大厂真题实战演练" },
          { text: "20 代码之外，技术面试中你应该具备哪些软素质？", icon: "pen-to-square", link: "20 代码之外，技术面试中你应该具备哪些软素质？" },
          { text: "21 面试中如何建立全局观，快速完成优质的手写代码？", icon: "pen-to-square", link: "21 面试中如何建立全局观，快速完成优质的手写代码？" },
          { text: "加餐 课后练习题详解", icon: "pen-to-square", link: "加餐 课后练习题详解" },
        ],
      },
      {
        text: "苹果",
        icon: "pen-to-square",
        prefix: "apple/",
        children: [
          { text: "苹果1", icon: "pen-to-square", link: "1" },
          { text: "苹果2", icon: "pen-to-square", link: "2" },
          "3",
          "4",
        ],
      },
      {
        text: "香蕉",
        icon: "pen-to-square",
        prefix: "banana/",
        children: [
          {
            text: "香蕉 1",
            icon: "pen-to-square",
            link: "1",
          },
          {
            text: "香蕉 2",
            icon: "pen-to-square",
            link: "2",
          },
          "3",
          "4",
        ],
      },
      { text: "樱桃", icon: "pen-to-square", link: "cherry" },
      { text: "火龙果", icon: "pen-to-square", link: "dragonfruit" },
      "tomato",
      "strawberry",
    ],
  },
  {
    text: "V2 文档",
    icon: "book",
    link: "https://theme-hope.vuejs.press/zh/",
  },
]);
